{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auth.fullname" . }}-ingress
spec:
  rules:
    {{- range .Values.ingress.rules }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .http.paths }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .service.name }}
            port:
              number: {{ .service.port }}
      {{- end }}
    {{- end }}
  ingressClassName: nginx
{{- end }}
