apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ include "auth.fullname" . }}
    app: auth
  ports:
    - protocol: TCP
      name: web
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}} 
  type: {{.Values.service.type}} 
